In [4]:
import numpy as np

def create_matrix(kon, kappa):
    # Identity matrices
    I_kon = np.eye(kon)  # kon x kon identity matrix
    I_1 = np.eye(1)      # 1 x 1 identity matrix
    I_kappa_kon = np.eye(kappa - kon)  # (kappa-kon) x (kappa-kon) identity matrix

    # Zero matrices
    Z_11 = np.zeros((kon, 1))
    Z_13 = np.zeros((kon, kappa - kon))
    Z_22 = np.zeros((1, kon))
    Z_23 = np.zeros((1, kappa - kon))
    Z_31 = np.zeros((kappa - kon, 1))
    Z_32 = np.zeros((kappa - kon, kon))

    # Assemble the block matrix
    matrix = np.block([
        [Z_11, I_kon, Z_13],
        [I_1, Z_22, Z_23],
        [Z_31, Z_32, I_kappa_kon]
    ])

    return matrix

# Example usage
kon = 3
kappa = 7
result = create_matrix(kon, kappa)
print("Generated Matrix:")
print(result)


Generated Matrix:
[[0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [6]:
import numpy as np
import redis
import pickle


rs = redis.StrictRedis(host='172.18.0.1',port=6379,db=2,password="chlpw1039") 
print(pickle.loads(rs.mget(f'error_1_2_0')[0]))

TypeError: a bytes-like object is required, not 'NoneType'